### ISSUE TITLE
Library doesn't work in NodeJS

### ISSUE THREAD

**Issue by DominikPalo** [attendease/attendease-js#10]
I'm trying to use this library in my NodeJS project, but after installing attendease using `npm install attendease`, library doesn't work. 

`require('attendease')` imports only empty object `{}` (so trying to call `require('attendease')('mydomain')` fails with `TypeError: object is not a function`. 

I solved it by specifying relative path: `var attendease = require('./node_modules/attendease/src/attendease.js')('mydomain)`, so `attendease` now contains the Attendease client, but `attendease.login({/*my credentials*/})` fails with:

```
C:\Projects\attendease_test\node_modules\attendease\src\client
\auth.js:21
  var def = $.Deferred()
            ^
ReferenceError: $ is not defined
    at Client.exports.logout (C:\Projects\attendease_test\node
_modules\attendease\src\client\auth.js:21:13)
    at Client.exports.login (C:\Projects\attendease_test\node_
modules\attendease\src\client\auth.js:3:8)
    at Object.<anonymous> (C:\Projects\attendease_test\index.j
s:8:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by mikeric** [comment]
Hi @DominikPalo. Thanks for opening this. I've just released 1.0.0 and it should work fine in Node now. There is no longer a jQuery dependency and you should be able to just `require('attendease')` normally.

Let us know if you run into any other issues or have any questions.
